

# Semana 1: Los Computadores



### 1.1. Historia de los computadores

El hombre debido a su condición innata de investigar y resolver problemas, ve la necesidad de hacer cálculos. Desde siglos antes de Cristo el hombre empezó a calcular de forma muy rudimentaria pero eficaz usando los dedos de las manos. Al ver que ésta técnica no era suficiente para resolver problemas de cálculos más complejos, en Egipto y China se ideó el ábaco, con el cual se puede realizar sumas y restas. El **ábaco** es considerado como el primer dispositivo de cómputo que precedió a la computadora. En 1960 el matemático y filósofo francés Blaise Pascal produjo una máquina de cálculo mecánica llamada **Pascalina** que funcionaba con ruedas y engranajes, con el fin de ayudar a su padre en las labores cómo recaudador de impuestos, que le requerían efectuar un gran numero de cálculos aritméticos cotidianamente. La primera computadora análoga utilizada de manera amplia y extensiva fue la **regla de cálculo** inventa en el siglo XVII, la cual es un instrumento de cálculo aritmético que permitía hacer cálculos más complejos cómo potenciación, función trigonométrica, logaritmos, entre otros. Sin embargo, el hombre no solo ha necesitado instrumentos para ayudarse a contar, sino también formas de registrar información. En el siglo *XX* se desarrollaron las primeras computadoras automáticas que hacían posible la aplicación de decisiones lógicas durante el cálculo de los datos; éstas computadoras eran de un tamaño enorme, muy inflexibles, pero con un aumento muy sustancial en la velocidad de procesos de operación.



### 1.2. Partes y funciones de la computadora


1. Pantalla: Visualizador que muestra al usuario los resultados del procedimiento de una operación.
2. Tarjeta madre: A ella se conectan todos los componentes del computador para poder interpretar las instrucciones contenidas en los programas
3. Procesador / CPU (Unidad central de procesamiento): Contiene todos los circuitos que guardan los datos para controlar, interpretar y ejecutar las instrucciones que envían los usuarios.
4. Memoria RAM (Memoria de acceso aleatorio): Almacena las instrucciones de los programas y la información que entra a través de los dispositivos, se le conoce cómo memoria volátil ya que cada vez que se apaga los datos desaparecen, hasta que se vuelve a usar.
5. Puertos PCI (Interconexión de componentes periféricos): Conecta distintos dispositivos periféricos directamente a la placa base. Por ejemplo, tarjeta de video, audio, red, entre otros.
6. Fuente de alimentación de energía: Convierte la energía suministrada desde la corriente del toma (señal alterna) en corriente directa (señal continua) para cada uno de los dispositivos.
7. Unidad óptica de almacenamiento: Es una unidad de discos que usa luz láser como parte del proceso de lectura o escritura de datos.
8. Disco duro: Dispositivo de almacenamiento que emplea un sistema de grabación magnética para almacenar datos digitales. Se conoce cómo un dispositivo de almacenamiento permanente.
9. Teclado: Dispositivo que permite introducir datos u órdenes, está inspirado en la máquina de escribir
10. Ratón: Dispositivo apuntador.



### 1.3. Almacenamiento de la información
*   **La memoria ROM** (Read-Only Memory) guarda información que NO cambia. La memoria contenida en ésta no puede ser modificada. Almacena, por ejemplo, los programas que se deben iniciar al prender el computador.
*   **La memoria RAM** (Random Access Memory) almacena temporalmente información que puede ser modificada en cualquier momento. La información en la memoria RAM se pierde cuando se apaga el computador.

La información en un computados se mueve a través del bus, el cual es un sistema de interconección del procesador con los dispositivos de entrada/salida y la memoria. Por este bus icirculan datos, señales de control o direcciones de memoria; de acuerdo a éstas funciones ecxisten tres tipos de buses

*   **Bus de datos:** Permite transportar datos entre las componentes de la computadora a través de un circuito impreso. El ancho del bus de datos permite saber la cantidad de máxima información que se puede transportar en un segundo.
*   **Bus de direcciones:** Permite indicar el origen y destino de los datos.
*   **Bus de control:** Proporciona señales para coordinar las diferentes tareas, sin que haya colisión de información.

<p><a name="Turing"></a></p>

## 1.4. Máquinas de Turing

Hemos visto como la interpretación de los problemas como algoritmos fue introducido por el matemático árabe Al'Juarismi (Abu Abdallah Muḥammad ibn Mūsā al-Jwārizmī--780 AC, . 850 AC), sin embargo sus desarrollos matemáticos no habían sido pensados como una implementación para que una máquina resolviera de forma automática el algoritmo. No fue sino hasta 1953 DC, que el matemático Alan Turing describiera una técnica para que un sistema artificial pudiera resolver la mayoría de los problemas lógicos y matemáticos, lo cual formaliza el concepto de algoritmo computacional.

Una máquina de Turing es un dispositivo que manipula símbolos sobre una tira de cinta de acuerdo con una tabla de reglas. A pesar de su simplicidad, una máquina de Turing puede ser adaptada para simular la lógica de cualquier algoritmo de computador y es particularmente útil en la explicación de las funciones de una CPU dentro de un computador.
La máquina de Turing no está diseñada como una tecnología de computación práctica, sino como un dispositivo hipotético que representa una máquina de computación. Las máquinas de Turing ayudan a los científicos a entender los límites del cálculo mecánico.
La importancia de la máquina de Turing en la historia de la computación es doble: primero, la máquina de Turing fue uno de los primeros (si no el primero) modelos teóricos para las computadoras, viendo la luz en 1936. Segundo, estudiando sus propiedades abstractas, la máquina de Turing ha servido de base para mucho desarrollo teórico en las ciencias de la computación y en la teoría de la complejidad. Una razón para esto es que las máquinas de Turing son simples, y por tanto amenas al análisis.

De manera formal la máquina de Turing se define como

MT=(Q,Σ,Γ,Q0,b,F,δ),

En donde:
Q es un conjunto finito de estados posibles para la máquina de Turing.

Σ es un conjunto finito de símbolos distinto del espacio en blanco, denominado alfabeto de máquina o de entrada.

Γ es un conjunto finito de símbolos de cinta, denominado alfabeto de cinta
Q0 es el estado inicial.

b es un símbolo denominado blanco, y es el único símbolo que se puede repetir un número infinito de veces.

F es el conjunto de estados finales de aceptación.

δ:Q×Γ→Q×Γ×{L,R,S}  es una función parcial denominada función de transición, donde L es un movimiento a la izquierda, R es el movimiento a la derecha y S es de no movimiento.

Existen muchos tipos de Maquinas de Turing como por ejemplo MT unidireccional en donde la cinta avanza en un solo sentido pero no puede retroceder, MT bidireccional en donde la cinta puede avanzar y retoceder (la más común), MT multicinta en donde la máquina posee dos o más cintas para leer y/o escribir los estados, MT multidimensional en donde existe "una cinta" de n-dimensiones, un caso sencillo sería un plano. En cada una de ellas hay que establecer las reglas de funcionamiento, a esto le llamaremos codificación de la MT.

Codificación de MT bidireccional.

Para realizar la codificación debemos hacer explícito cada uno de los elementos de la MT. Entonces asumamos, como ejemplo lo siguiente:

Q={pi,qi} los estados de entrada y salida.

Σ={0,1,∗} los símbolos de máquina, representando los digitos binarios y * dependiendo si ocupa valor o proximo estado puede signifiar cualquier valor, dejar inalterado el valor o no mover (movimiento S).

Γ={0,1,∗} los símbolos en la cinta, representando los digitos binarios y * dependiendo si ocupa valor o proximo estado puede signifiar cualquier valor, dejar inalterado el valor o no mover (movimiento S).


Q0={0} es el estado inicial.

b={_} es el símbolo de espacio en blanco.

F={Halt} es el estado de parada.

δ=EstadoActual, ValorActual, NuevoValor, MovimientoCinta, PróximoEstado. Es la función de transición.
Con esto en mente codifiquemos  una MT que calcule el complemento a 1 (C1) de cualquier número binario.
*Solución*. Usando la definición de MT anterior se tiene que:

0 0 1 R 0

0 1 0 R 0

0 _ * L Halt

Vemos que sólo se rerequiere del estado inicial para resolver este problema. Comprobemos nuestra máquina de turing (MT) con algún valor particular, por ejemplo, 1010. Entonces la MT realizará una secuencia de pasos determinados por la función de trancisión así:

Paso 1: **1**010. Este es el primer paso, el valor actual es 1, por lo que se cambiará por el valor de 0, de acuerdo a la función de transición, luego de cambiar el valor se mueve un espacio a la derecha quedando en el estado 0 nuevamente

Paso 2: 0**0**10. En este paso, el valor actual es 0, por lo que se cambiará por 1. Luego de cambiar el valor se mueve un espacio a la derecha y queda en el estado 0.

Paso 3: 01**1**0. Aquí, nuevamente el valor actual es 1, por lo que se cambiará por 0, se moverá a la derecha y quedará en estado 0.

Paso 4: 010**0**. Aquí, el valor actual es 0, se cambiará por 1 y se moverá a la derecha, quedando en el estado 0.

Paso 5: 0101**_**. En este lugar el valor atual es el espacio, se deja inalterado, se mueve a la izquierda y se detiene la MT.

De acuerdo a esto, a la MT ingresa 1010 y esta devuelve 0101.



### 1.5. Sistemas Numericos y código binario

### 1.5.1. Los números y representación de cantidades

Los números nacen como una consecuencia natural de la invensión del lenguage, podríamos decir que las civilizaciones tuvieron su desarrollo tan acelerado después de inventar la manera en que las historias quedaran registradas de forma permanente en un objeto físico, es decir, una tablilla de piedra, una hoja de papiro, un jarro de arcilla, etc. Con la invención de la esritura surgen los símbolos necesario para contar y establecer la relación directa entre cantidad y el símbolo. Inicialmente los números no surgieron para satisfacer la necesidad de escribir axiomas o teorías matematicas complejas sino por algo más banal como saber cuantas cabras o gallinas se tenían. Otra cosa importante es que las civilizaciones antiguas no necesariamente contaban como lo hacemos hoy en día, es decir con diez símbolos para representar cantidades. Muchas contaban con distintas bases, por ejemplo los Babilonios tenían dos bases una de 10 y otra de 60 para contar, los Chinos usaban una base de 10 para contar y una base de 2 para las cábalas. Los Mayas una base de 20 y otra de 5. Pero es cierto que la mayoría de las civilizaiones, Romanos, Griegos, Arabes, han contado con bases de 10; tal vez obedeciendo al hecho de que en las manos tenemos 10 dedos.
Ahora veamos como se cuenta en algunas bases distintas.
Supongamos que tenemos la siguiente figura que representa un cargamento de piedras preciosas de gran valor, debemos informar cuántas de ellas hay

Lo primero que haremos será definir un conjunto de simbolos para representar las cantidades básicas, por ejemplo 0,1,2,3; y para componer números más grandes usaremos una notación posicional, o sea unidades, decenas, centenas, etc.
Como tenemos 4 símbolos hacemos empaques de 4 esferas y luego hacemos empaques mas grandes de 4 cuatro paquetes cada uno y así sucesivamente.

Como se puede ver, haciendo primeros empaques de 4 esferas nos quedan dos que no forman un empaque completo. Continuamos haciendo el procesos pero ahora con las cajas azules

Y vemos que sólo se pudo completar una caja roja con 4 azules. Por lo tanto estamos listos para decir que tenemos en totalidad la cantidad de esferas que caben en 1 caja roja, 3 cajas azules y 2 esferas sueltas. En este ejemplo el numero de elemnetos tomados para etiquetar es la base, osea 4. Entonces la cantidad de esferas contadas usando la base 4 sera de 132 esferas.

#### <center> Hablando en Binario
_________________________________________________________

El procesamiento de datos dentro de un computador tiene como base las **ALU(Arithmetic Logic Unit)** o unidades aritméticas lógicas. Una ALU debe procesar números usando el mismo formato que el resto del circuito digital.

Para los procesadores modernos, este formato casi siempre es la representación del número binario de complemento a dos conocido como **Formato IEEE 754**. Las primeras computadoras usaron una amplia variedad de sistemas de numeración, incluyendo complemento a uno, formato signo-magnitud, e incluso verdaderos sistemas decimales, con diez tubos por dígito [Ver más](https://es.wikipedia.org/wiki/Unidad_aritm%C3%A9tica_l%C3%B3gica#Operaciones_simples).

### 1.5.2 Sistemas de numeración

Un sistema de numeración es un conjunto de reglas y símbolos (por ejemplo los dígitos) que permiten construir un conjunto numérico, por ejemplo nuestro sistema decimal, el más usado en la actualidad, que nos permite organizar los números como la suma de los dígitos por potencias de 10:

$$
N_{b10} = \sum_{n=Q}^{n=P} a_n 10^n
$$

donde $\sum$ es el símbolo matemático que representa la suma de la secuencia en n desde un valor Q hasta P, donde $n \in Z$, tal que n puede ser positivo o negativo y $a_n \in \{0,1,2,3,4,5,6,7,8,9\}$, es decir $a_n$ es un dígito.

Ejemplo:

$$340.78 = 3*10^2 + 4*10^1 + 0*10^0 +7*10^{-1} + 8*10^{-2} \text{.}$$

En este caso vemos que P=2 y Q=-2

### 1.5.3. Sistema binario

El sistema binario sigue unas reglas parecidas al sistema decimal descrita en Eq. 1, pero sus dígitos sólo pueden ser 0 o 1 por lo tanto: $$N_{b2} = \sum_{n=Q}^{n=P}  a_n 2^n $$

donde $n \in Z$, enteros desde un valor Q hasta P $a_n \in \{0,1\}\text{.}$

Ejemplo:

$$100.01 = 1*2^2 + 0*2^1 + 0*2^0 +0*2^{-1} + 1*2^{-2} \text{.}$$

En este caso vemos que P=2 y Q=-2

### Entero base 10 a Entero base 2

Para hallar los dígitos adecuados tenemos varios métodos: por asignación de potencias usando una tabla, por residuos o por logaritmos.

### Residuo

El método de residuo nos sugiere que tomemos nuestro número Z=149, y dividamos de forma entera por la base 2. Ya que los dígitos siempre son menores que su base (Ej, $0...9 <10$) y aprovechando la regla:

> Una división entre dos enteros N y M puede representarse como $\frac{N}{M} = C + \frac{R}{M}$, donde C es el cociente (número entero) y R el residuo(número entero)

Tendríamos

$$\dfrac{Z_{b10}}{2} = \sum_{0}^{P} \dfrac{a_n}{2} 2^n $$

Dado a que $a_n$ es un dígito menor que la base esta fracción será menor que 1 para la potencia $n=0$.  tenemos que:  

$$\dfrac{Z_{b10}}{2}= C_{b10} + \dfrac{R_{b10}}{2} = \dfrac{a_0}{2} + \sum_{n=1} \dfrac{a_n}{2} 2^n $$

Entonces, tendríamos un entero más un número racional menor que uno, dado que sólo $a_0/2$ puede ser racional, entonces el residuo sería el último dígito. Ahora volvemos a tener la misma situación:

$$\dfrac{C_{b10}}{2}= \sum_{n=1} \dfrac{a_n}{2} 2^n $$

Por lo cuál un método simple para pasar un entero de una base a otra es dividir por la base cada cociente resultante hasta que sea posible y guardando los residuos para ser organizados del último al cociente final.

In [ ]:
import pandas as pd
N=149
c = [N]
r = []
i=0
while c[-1]>1:
    c.append(c[i]//2)
    r.append(c[i]%2)
    i+=1
r.append(c[-1])
print("El número",N,"en base dos es:",r[::-1])
pd.DataFrame({"Operación":["%d/2"%(c[i]) for i in range(len(c))],
              "Cociente":["0" if i==len(c)-1 else c[i+1] for i in range(len(c))],"Residuo":r})

El número 149 en base dos es: [1, 0, 0, 1, 0, 1, 0, 1]

  Operación Cociente  Residuo
0     149/2       74        1
1      74/2       37        0
2      37/2       18        1
3      18/2        9        0
4       9/2        4        1
5       4/2        2        0
6       2/2        1        0
7       1/2        0        1

### Logaritmo

A pesar que el anterior método es bastante simple y fácil de programar, para números muy grades o pequeños puede ser demasiado complicado. Combinando el primer método y el segundo podemos hallar la representación binaria con mayor facilidad, sólo necesitamos saber cuál es la máxima potencia posible y desde allí restar y volver a encontrar la potencia, es un proceso en donde nos interesan los números fuera del 0, que no aporta a la suma, en el caso del sistema binario es muy bastante útil y práctico.

Es posible saber la potencia máxima posible con la que puede restarse nuestro número si este puede escribirse como $N=2^k$, siendo k un número real positivo, dado a que buscamos $N \geq 2^n$ entonces $2^k \geq 2^n$ lo que significa que $k \geq n$, si encontramos k y lo redondeamos al entero menor podremos hallar la representación más rápido.

$$k = \log_{2} N = \dfrac{\ln N}{\ln 2} = \dfrac{\log N}{\log 2}$$

In [ ]:
import math

n = []
k = []
resta = [N]
i=0
while resta[i]>0:
    k.append((math.log(resta[i])/math.log(2)))
    n.append(math.trunc(k[i]))
    resta.append(resta[i] - 2**n[i])
    i+=1

bin_str=[0]*n[0]
for p in n:
    bin_str[p-1] = 1
print("El número",N,"en base dos es:",bin_str[::-1])
pd.DataFrame({"Operación":["log(%d)/log(10)"%(resta[i]) for i in range(len(resta)-1)],
              "k":k,"n":n,"Falta":[resta[i] if i <= len(resta)-1 else 0 for i in range(1,len(resta))]})

El número 149 en base dos es: [1, 0, 0, 1, 0, 1, 0]

          Operación         k  n  Falta
0  log(149)/log(10)  7.219169  7     21
1   log(21)/log(10)  4.392317  4      5
2    log(5)/log(10)  2.321928  2      1
3    log(1)/log(10)  0.000000  0      0

### Enteros base 10 a otras bases

In [ ]:
N=149
c = [N]
r = []
i=0
while c[-1]>1:
    c.append(c[i]//5)
    r.append(c[i]%5)
    i+=1
r.append(c[-1])
print("El número",N,"en base 5 es:",r[::-1])
pd.DataFrame({"Operación":["%d/5"%(c[i]) for i in range(len(c))],
              "Cociente":["No" if i==len(c)-1 else c[i+1] for i in range(len(c))],"Residuo":r})

El número 149 en base 5 es: [1, 0, 4, 4]

  Operación Cociente  Residuo
0     149/5       29        4
1      29/5        5        4
2       5/5        1        0
3       1/5       No        1

In [ ]:
N=149
c = [N]
r = []
i=0
while c[-1]>1:
    c.append(c[i]//8)
    r.append(c[i]%8)
    i+=1
r.append(c[-1])
print("El número",N,"en base 8 es:",r[::-1])
pd.DataFrame({"Operación":["%d/8"%(c[i]) for i in range(len(c))],
              "Cociente":["No" if i==len(c)-1 else c[i+1] for i in range(len(c))],"Residuo":r})

El número 149 en base 8 es: [0, 2, 2, 5]

  Operación Cociente  Residuo
0     149/8       18        5
1      18/8        2        2
2       2/8        0        2
3       0/8       No        0

### Ejercicios enteros base 10 a base 2

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('XSF4z7l3Pf0')

### Fraccionarios base 10 a fraccionarios base 2

Para los números menores de 1 podemos aplicar más o menos los mismos métodos, tan sólo cambia el segundo método, **donde no dividimos sino que multiplicamos**, pero hay una diferencia principal y es que no podemos conocer la potencia mínima para representar un número real menor de 1 e incluso es posible que no podamos hacerlo con exactitud.

Los número enteros tiene la regla del cociente y residuo, cada vez que dividimos un número entero en la base a la que vamos a transformar se genera un par (C,R), ambos enteros, el residuo siempre es menor que la base y es un dígito en un orden especifico y el cociente puede volver a dividirse hasta que la división no pueda darnos un entero, entonce el último cociente (que obviamente es menor que la base) es tomado con los residuos y nos da la representación que queremos.

Pero con los racionales menores que 1, tenemos la serie

$$\sum_{n=-1} a_n 2^n \text{,} $$
que es una serie geométrica, tal que si todos los $a_n=1$ converge

$$\sum_{1}^M (1/2)^{k-1} = 1-2*(0.5)^M \text{,} $$

Entonces tenemos que la suma hasta cada potencia sería:

In [ ]:
import numpy as np
pd.DataFrame({"2^n":[2**(-m) for m in range(1,10)],"Suma 2^n":[1-2*(0.5)**m for m in range(2,11)]},index=np.arange(-1,-10,-1,dtype=np.int)).T

           -1    -2     -3      -4  ...        -6        -7        -8        -9
2^n       0.5  0.25  0.125  0.0625  ...  0.015625  0.007812  0.003906  0.001953
Suma 2^n  0.5  0.75  0.875  0.9375  ...  0.984375  0.992188  0.996094  0.998047

[2 rows x 9 columns]

Si partimos la serie en los valores acumulados por secciones, es probable que no podamos representar todos os fraccionarios con pocos números después de la coma, incluso es posible que tengamos que aproximar o redondear pues podríamos caer en un bucle infinito esperando poder hallar la representación exacta. Por ejemplo, el fraccionario 0.51

In [ ]:
N =np.longdouble(0.51)
r = []
i=0
resta=[N]
mul = []
while resta[-1]>0 and i<100:
    mul.append(resta[i]*np.longdouble(2.0))
    r.append(np.trunc(mul[i]))
    resta.append(mul[i]-r[i])
    i+=1

print("El número",N,"en base 2 es 0.",r)
pd.DataFrame({"Operación":["%f*2"%(resta[i]) for i in range(len(resta)-1)],
              "Resultado":mul,"Valores":r}).T

El número 0.5100000000000000089 en base 2 es 0. [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0]

                   0           1   ...          50          51
Operación  0.510000*2  0.020000*2  ...  0.250000*2  0.500000*2
Resultado        1.02        0.04  ...         0.5         1.0
Valores           1.0         0.0  ...         0.0         1.0

[3 rows x 52 columns]

Este fraccionario necesita de 51 números (dígitos entre 0 y 1) para poder representar con exactitud computacional el fraccionario, porque por supuesto cuando las operaciones tengan más de 16 dígitos después de la coma, el valor será naturalmente truncado, gracias al formato de representación de los procesadores actuales.

### Ejercicios con fraccionarios en base 10 a base 2

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('_YBhRnFOLpI')

### Números grandes y pequeños

Para los números grandes y pequeños lo más adecuado es usar el método logarítmico, siendo el número representado en su notación científica.

$$ A \times 10^P =2^k   \text{ primero calcule k como,  } \ k=\dfrac{\log(A)+P}{\log(2)} $$
$$  \text{ luego calcule , } n=[k] ,\text{ significa: } A \times 10^P = M \times 2^n $$
$$\text{  Donde  } M = \dfrac{A \times 10^P}{2^n}$$



Por ejemplo vamos a pasar a binario la masa de un electrón y la masa de la tierra.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('557cNM3Ea8g')

In [ ]:
N=9.1e-31
k=math.log(N)/math.log(2)
n=math.floor(k)
M=N/2**n
print("La masa de un electrón es:",N)
print("La mayor potencia es:",n)
print("El número en notación binaria es %fx2^(%d)"%(M,n))

In [ ]:
N=5.972e24
k=math.log(N)/math.log(2)
n=math.trunc(k)
M=N/2**n
print("La masa de la Tierra es:",N)
print("La mayor potencia es:",n)
print("El número en notación binaria es %fx2^(%d)"%(M,n))

### 1.5.4 Operaciones  aritmeticas con binarios

El sistema binario o también llamada diádico, es un sistema numérico que consta de dos cifras numéricas, normalmente el cero (0) y el uno (1). Por conveniencia se utiliza en los sistemas informáticos ya que la mayoría de estados físicos clásicos están muy bien definidos en dos estados posibles como por ejemplo encendido y apagado, una perforación o no, un voltaje alto o uno bajo, un estado magnetizado o desmagnetizado.

Los primeros en mencionar el sistema binario fueron los indios, lo que les permitió introducir el concepto del cero. Luego los chinos los cuales lo usaban como a manera de cábala. Pero fue el matemático  Leibniz, en el siglo XVII, en su artículo "Explication de l'Arithmétique Binaire" en el que  mencionan los símbolos binarios usados por matemáticos chinos. Leibniz utilizó el 0 y el 1, al igual que el sistema de numeración binario actual.

### Suma y Resta de binarios

La suma es una operación básica en donde se adicionan dos o más cantidades, que pueden ser de distintos conjuntos numéricos, para formar un total. Por ejemplo $5 + (-19) = -14$, donde es sistema es base 10 y es la suma de un natural y un entero negativo.

En los binarios también tenemos esta operación donde:

| + | 0  | 1  |  
|:-:|:-: |:-: |
| 0  |  0 | 1 |
| 1  |  1 | 10|

Al igual que en el sistema decimal cunado sumamos dos dígitos y debemos movernos en las potencias de 10, hacemos lo mismo en el binario sabemos que $1+1=2$ pero en el sistema binario esto se representa como $10$ por lo tanto el proceso es similar, donde ese 1 se guarda para la operación hacia la izquierda.

En contraposición la resta tiene la relación:

| - | 0  | 1  |  
|:-:|:-: |:-: |
| 0  |  0 | 1 |
| 1  |  -1 | 0|

Ese -1 muchas veces crea problemas, en el sistema decimal cuando se restaba $23 - 9$ donde 9 es mayor a 3, se decía que 2 le prestaba $1*10^1$ tal que se operaba $13 - 9 = 4$ y el $2$ se transformaba en 1. Es lo mismo en el mundo binario pero puede ser más complicado de ejecutar.
Una manera de lidiar con los dígitos que se "prestan" cuando la resta es positiva, dado que hacer el proceso de "prestar" cuando se resta un número "mayor" de uno "menor" es un poco confuso, se utiliza el concepto de complemento a dos, que básicamente es negar cada dígito del sustraendo  (C1) y luego sumar 1, para luego sumar el C2 al minuendo. Teniendo en cuenta que se quita al final el bit mas significativo.

Ejemplo: calcular el complemento a 2 (C2) de 11000

Solución:

|Número|1|1|0|0|0|
|:-:   |:-:|:-:|:-:|:-:|:-:|
|C1    |0|0|1|1|1|
|suma 1|0|0|0|0|1|  
|C2    |0|1|0|0|0|  


Ejemplo: restar 11001 de 10000000
Solución: Lo primero es calcular el C2 de 11001 usando el mismo número de dígitos que el minuendo, así C2:  11100111, ahora sumarlo al minuendo

| se lleva |1  |   |   |   |   |   |   |   |   |
|:-:       |:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| Minuendo |   | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
|    C2    |   | 1 | 1 | 1 | 0 | 0 | 1 | 1 | 1 |
| Resultado|   | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 1 |



### Multiplicación de binarios

La multiplicación en binario es más fácil que en cualquier otro sistema de numeración. Como los factores de la multiplicación sólo pueden ser CEROS o UNOS, el producto sólo puede ser CERO o UNO. En otras palabras, las tablas de multiplicar del cero y del uno son muy fáciles de aprender:

| * | 0  | 1  |  
|:-:|:-: |:-: |
| 0  |  0 | 0 |
| 1  |  0 | 1|

### División entera de binarios

La división se realiza de la misma manera, pero se puede ayudar del complemento a 2 para realizar las restas. Estas se hacen sucesivamente hasta que ya no se pueda restar más el divisor. Por ejemplo dividir 11011 entre 101:

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('S84ai9mPzGk')

### 1.5.5. Formato IEEE 754

> El estándar del IEEE para aritmética en coma flotante (IEEE 754) es la norma o estándar técnico para computación en coma flotante, establecida en 1985 por el Instituto de Ingenieros Eléctricos y Electrónicos (IEEE). La norma abordó muchos problemas encontrados en las diversas implementaciones de coma flotante que las hacían difíciles de usar de forma fiable y portátil. Muchas unidades de coma flotante de hardware utilizan ahora el estándar IEEE 754. [Ver más](https://es.wikipedia.org/wiki/IEEE_coma_flotante)

Si bien el formato IEEE 754 incluye varias normas para la asignación de números, números especiales, limites y demás. Es tan sólo un paso más para tener una representación adecuada según el bus de datos que se conecta al procesador y mueve las entradas y salidas. Básicamente la idea es representar por un número fijo de bits el signo, el exponente (en notación científica binaria, generalmente con un sesgo) y la mantisa (los decimales después de la coma). [Ver tabla](https://es.wikipedia.org/wiki/IEEE_coma_flotante)

<table class="wikitable">
<tbody><tr>
<th>Nombre
</th>
<th>Nombre común
</th>
<th>Base
</th>
<th>Dígitos (1 signo)
</th>
<th>Dígitos
<p>decimales
</p>
</th>
<th>Bits del Exponente
</th>
<th>E<sub>max</sub>
<p>Decimal
</p>
</th>
<th>Sesgo del
<p>Exponente
</p>
</th>
<th>E<sub>min</sub>
</th>
<th>E<sub>max</sub>
</th>
<th>Notas
</th></tr>
<tr>
<td>binary16
</td>
<td>Media precisión
</td>
<td align="right">2
</td>
<td align="right">11
</td>
<td align="right">~3
</td>
<td align="right">5
</td>
<td align="right">4,51
</td>
<td>2<sup>4</sup>−1 = 15
</td>
<td align="right">−14
</td>
<td align="right">+15
</td>
<td>No básico
</td></tr>
<tr>
<td>binary32
</td>
<td>Simple precisión
</td>
<td align="right">2
</td>
<td align="right">24
</td>
<td align="right">~7
</td>
<td align="right">8
</td>
<td align="right">38,23
</td>
<td>2<sup>7</sup>−1 = 127
</td>
<td align="right">−126
</td>
<td align="right">+127
</td>
<td>
</td></tr>
<tr>
<td> binary64
</td>
<td>Doble precisión
</td>
<td align="right">2
</td>
<td align="right">53
</td>
<td align="right">~16
</td>
<td align="right">11
</td>
<td align="right">307,95
</td>
<td>2<sup>10</sup>−1 = 1023
</td>
<td align="right">−1022
</td>
<td align="right">+1023
</td>
<td>
</td></tr>
<tr>
<td>binary128
</td>
<td>Cuádruple precisión
</td>
<td align="right">2
</td>
<td align="right">113
</td>
<td align="right">34,02
</td>
<td align="right">15
</td>
<td align="right">4931,77
</td>
<td>2<sup>14</sup>−1 = 16383
</td>
<td align="right">−16382
</td>
<td align="right">+16383
</td>
<td>
</td></tr>
<tr>
<td>binary256
</td>
<td>Óctuple precisión
</td>
<td align="right">2
</td>
<td align="right">237
</td>
<td align="right">71,34
</td>
<td align="right">19
</td>
<td align="right">78913,20
</td>
<td>2<sup>18</sup>−1 = 262143
</td>
<td align="right">−262142
</td>
<td align="right">+262143
</td>
<td>No básico
</td></tr>
<tr>
<td>
</td></tr></tbody></table>

Para mayor referencia puede ver ejemplos aqui: [Conversion de decimal a binary32 en Wikipedia](https://https://es.wikipedia.org/wiki/Formato_en_coma_flotante_de_simple_precisi%C3%B3n#Ejemplos_de_conversi%C3%B3n_de_n%C3%BAmeros_decimales_a_formato_binary32)